### ISSUE TITLE
How to get ENCRYPTION_TOKEN

### ISSUE THREAD

**Issue by felodel** [killbill/killbill-adyen-demo#4]
When I try to execute app.r, I don´t know how to get ENCRYPTION_TOKEN.

Furthermore, when I run application, I get next error:

2019-10-01 03:26:30 - KillBillClient::API::BadRequest - {"className":"java.lang.NullPointerException","code":null,"message":null,"causeClassName":null,"causeMessage":null,"stackTrace":[]}:
	/home/fermax/.gem/gems/killbill-client-3.0.0/lib/killbill_client/api/net_http_adapter.rb:225:in `request'
	/home/fermax/.gem/gems/killbill-client-3.0.0/lib/killbill_client/api/api.rb:49:in `post'
	/home/fermax/.gem/gems/killbill-client-3.0.0/lib/killbill_client/models/resource.rb:48:in `post'
	/home/fermax/.gem/gems/killbill-client-3.0.0/lib/killbill_client/models/hosted_payment_page.rb:12:in `build_form_descriptor'
	app.rb:82:in `directory_lookup'
	app.rb:175:in `block in <main>'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `block in compile!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1006:in `route_eval'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1035:in `block in process_route'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `catch'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `process_route'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:985:in `block in route!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `each'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `route!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1094:in `dispatch!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `block in call!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `call!'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:908:in `call'
	/home/fermax/.gem/gems/rack-protection-2.0.7/lib/rack/protection/xss_header.rb:18:in `call'
	/home/fermax/.gem/gems/rack-protection-2.0.7/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/fermax/.gem/gems/rack-protection-2.0.7/lib/rack/protection/json_csrf.rb:26:in `call'
	/home/fermax/.gem/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
	/home/fermax/.gem/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
	/home/fermax/.gem/gems/rack-protection-2.0.7/lib/rack/protection/frame_options.rb:31:in `call'
	/home/fermax/.gem/gems/rack-2.0.7/lib/rack/logger.rb:15:in `call'
	/home/fermax/.gem/gems/rack-2.0.7/lib/rack/common_logger.rb:33:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:231:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:224:in `call'
	/home/fermax/.gem/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/home/fermax/.gem/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/show_exceptions.rb:22:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:194:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1950:in `call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `block in call'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1729:in `synchronize'
	/home/fermax/.gem/gems/sinatra-2.0.7/lib/sinatra/base.rb:1502:in `call'
	/home/fermax/.gem/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
	/snap/ruby/151/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
	/snap/ruby/151/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
	/snap/ruby/151/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [01/Oct/2019:03:26:29 PDT] "GET / HTTP/1.1" 500 144789

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
